apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hp2lfl1rz-python 
  janus-idp.io/tekton: hp2lfl1rz-python
  backstage.io/kubernetes-id: hp2lfl1rz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hp2lfl1rz-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  