apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hp2lfl1rz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hp2lfl1rz-python 
  name: hp2lfl1rz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hp2lfl1rz-python 
